# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
units: bin/units.tsv

ref:
  # path/to/reference/gDNA.fasta
  sequence:       /varidata/research/projects/bbc/versioned_references/2021-08-10_11.12.27_v6/data/mm10_gencode/sequence/mm10_gencode.fa
  fai:            /varidata/research/projects/bbc/versioned_references/2021-08-10_11.12.27_v6/data/mm10_gencode/sequence/mm10_gencode.fa.fai
  # path/to/STAR/index/directory
  index:          /varidata/research/projects/bbc/versioned_references/2021-08-10_11.12.27_v6/data/mm10_gencode/indexes/star
  salmon_index:   /varidata/research/projects/bbc/versioned_references/2021-08-10_11.12.27_v6/data/mm10_gencode/indexes/salmon/mm10_gencode
  # path/to/gtf/file/with/transcripts.gtf
  annotation:     /varidata/research/projects/bbc/versioned_references/2021-08-10_11.12.27_v6/data/mm10_gencode/annotation/mm10_gencode.gtf
  # known variants (Broad resource downloaded here: https://console.cloud.google.com/storage/browser/genomics-public-data/resources/broad/mm10/v0/)
  known_snps:
  known_indels:
  snpeff_db_id:
# are the sequencing reads paired-end ('PE') or single-end ('SE')
PE_or_SE: PE

# what is the strandedness of the kit used for library prep?
# options: "forward", "reverse", "unstranded" (usually reverse)
strandedness: reverse


# Boolean for whether to call variants. Requires 'variant_calling_units.tsv'
# snpRelate html report only generated if conda is callable. Otherwise, the snpRelate rule is not run.
call_variants: false


sortmerna:
    rfam5_8s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5.8s-database-id98.fasta
    rfam5s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5s-database-id98.fasta
    silva_arc_16s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-16s-id95.fasta
    silva_arc_23s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-23s-id98.fasta
    silva_bac_16s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/silva-bac-16s-id90.fasta
    silva_bac_23s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/silva-bac-23s-id98.fasta
    silva_euk_18s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-18s-id95.fasta
    silva_euk_28s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-28s-id98.fasta
    idx_dir: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/indexes/idx/

modules:
  fastq_screen: bbc2/fastq_screen/fastq_screen-0.14.0
  gatk: bbc2/gatk/gatk-4.3.0.0
  htslib: bbc2/htslib/htslib-1.17
  multiqc: bbc2/multiqc/multiqc-1.14
  picard: bbc2/picard/picard-2.27.5
  R: bbc2/R/alt/R-4.2.1-setR_LIBS_USER
  salmon: bbc2/salmon/salmon-1.10.0
  samtools: bbc2/samtools/samtools-1.17
  seqtk: bbc2/seqtk/seqtk-1.3-r115-dirty
  snpeff: bbc2/SnpEff/SnpEff-5.1
  sortmerna: bbc2/sortmerna/sortmerna-4.3.6
  star: bbc2/STAR/STAR-2.7.10a
  trim_galore: bbc2/trim_galore/trim_galore-0.6.10
  vt: bbc2/vt/vt-0.1.16
