ref:
  index:          /varidata/research/projects/bbc/versioned_references/2023-05-03_15.28.41_v12/data/hg38_gencode/indexes/star
  salmon_index:   /varidata/research/projects/bbc/versioned_references/2023-05-03_15.28.41_v12/data/hg38_gencode/indexes/salmon/hg38_gencode
  annotation:     /varidata/research/projects/bbc/versioned_references/2023-05-03_15.28.41_v12/data/hg38_gencode/annotation/hg38_gencode.gtf

# OrgDB R package for covnerting gene names. Common choices are 'org.Mm.eg.db' for mouse and 'org.Hs.eg.db' for human.
orgdb: org.Hs.eg.db

# are the sequencing reads paired-end ('PE') or single-end ('SE')
PE_or_SE: PE

####################################################################
# FOR MOST STANDARD USE CASES, THE BELOW DO NOT NEED TO BE CHANGED.#
####################################################################

# path to sample sheet relative to the base project directory (containing config/, workflow/ etc)
units: config/samplesheet/units.tsv

sortmerna:
    rfam5_8s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5.8s-database-id98.fasta
    rfam5s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/rfam-5s-database-id98.fasta
    silva_arc_16s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-16s-id95.fasta
    silva_arc_23s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/silva-arc-23s-id98.fasta
    silva_bac_16s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/silva-bac-16s-id90.fasta
    silva_bac_23s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/silva-bac-23s-id98.fasta
    silva_euk_18s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-18s-id95.fasta
    silva_euk_28s: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/rRNA_databases/silva-euk-28s-id98.fasta
    idx_dir: /varidata/research/software/BBC/sortmerna/sortmerna-4.3.6-Linux/indexes/idx/

modules:
  deeptools: bbc2/deeptools/deeptools-3.5.2
  fastq_screen: bbc2/fastq_screen/fastq_screen-0.14.0
  gatk: bbc2/gatk/gatk-4.3.0.0
  htslib: bbc2/htslib/htslib-1.17
  multiqc: bbc2/multiqc/multiqc-1.14
  picard: bbc2/picard/picard-2.27.5
  R: bbc2/R/alt/R-4.2.1-setR_LIBS_USER
  salmon: bbc2/salmon/salmon-1.10.0
  samtools: bbc2/samtools/samtools-1.17
  seqtk: bbc2/seqtk/seqtk-1.3-r115-dirty
  sortmerna: bbc2/sortmerna/sortmerna-4.3.6
  star: bbc2/STAR/STAR-2.7.10a
  trim_galore: bbc2/trim_galore/trim_galore-0.6.10
