$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:

  samples:
    type: string

  contrasts:
    type: string

  ref:
    type: object
    properties:
      index:
        type: string
      annotation:
        type: string
    required:
      - index
      - annotation

  PE_or_SE:
    type: string

  species:
    type: object
    properties:
      short:
        type: string
      long:
        type: string

  annotation:
    type: string

  logfc.filter:
    type: string
  fdr.filter:
    type: string

required:
  - units
  - contrasts
  - ref
  - species
  - annotation
  - logfc.filter
  - fdr.filter
