$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:

  samples:
    type: string

  contrasts:
    type: string

  ref:
    type: object
    properties:
      index:
        type: string
      annotation:
        type: string
    required:
      - index
      - annotation

  PE_or_SE:
    type: string
    enum:
      - PE
      - SE

  strandedness:
    type: string
    enum:
      - unstranded
      - forward
      - reverse

  species:
    type: object
    properties:
      short:
        type: string
      long:
        type: string

  annotation:
    type: string
    enum:
      - org.Hs.eg.db
      - org.Mm.eg.db

  logfc.filter:
    type: number
  fdr.filter:
    type: number

required:
  - units
  - contrasts
  - ref
  - species
  - strandedness
  - annotation
  - logfc.filter
  - fdr.filter
