# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: src/samples.tsv
# path or URL to contrast sheet (TSV format, columns: sample, condition, ...)
contrasts: src/contrasts.tsv

units: src/units.tsv

ref:
  # the STAR index
  index: /primary/projects/bbc/references/mouse/indexes/mm10/star/star_p1idx
  # gtf file with transcripts
  annotation: /primary/projects/bbc/references/mouse/annotation/mm10/ensembl/Mus_musculus.GRCm38.86.gtf

# two-letter species annotation for (e.g. "Hs" <- Human)
org: Mm

# org.db package used for annotation (e.g. "org.eg.Hs.db" for Human)
# see edger.yaml for supported species packages
annotation: org.eg.Mm.db
