# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
units: src/units.tsv
# path or URL to contrast sheet (TSV format, columns: sample, condition, ...)
contrasts: src/contrasts.tsv

ref:
  # path/to/STAR/index/directory
  index: /primary/projects/bbc/references/mouse/indexes/mm10/star/star_p1idx
  # path/to/gtf/file/with/transcripts.gtf
  annotation: /primary/projects/bbc/references/mouse/annotation/mm10/ensembl/Mus_musculus.GRCm38.86.gtf

# are the sequencing reads paired-end ('PE') or single-end ('SE')
PE_or_SE: SE

### EdgeR Variables ###

# two-letter species annotation for (e.g. "Hs" <- Human)
species:
  # (e.g. Human -> "hsapiens")
  short: mmusculus
  # (e.g. Human -> "Homo sapiens")
  long: Mus musculus
# org.db package used for annotation (https://www.bioconductor.org/packages/release/BiocViews.html#___OrgDb)
annotation: org.Mm.eg.db
# differential expression cutoff values
logfc.filter: 0.58
fdr.filter: 0.05
