# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: src/samples.tsv
# path or URL to contrast sheet (TSV format, columns: sample, condition, ...)
contrasts: src/contrasts.tsv

units: src/units.tsv

ref:
  # the STAR index
  index: /primary/projects/bbc/references/human/indexes/hg38/hg38_STAR/
  # gtf file with transcripts
  annotation: /primary/projects/bbc/references/human/annotation/hg38/ensembl/Homo_sapiens.GRCh38.87.chr.gtf

# two-letter species annotation for (e.g. "Hs" <- Human)
org: Hs

# org.db package used for annotation (e.g. "org.eg.Hs.db" for Human)
# see edger.yaml for supported species packages
annotation: org.eg.Hs.db
